In [1]:
from methods import *

In [2]:
(
    m,
    loader,
    optim,
    model,
    num_domain,
    num_group,
    lr_scheduler,
    device,
    n,
    num_feature,
    num_class,
) = exp_init(
    'waterbirds',
    128,
    'y',
    'a',
    0,
    0,
    'fairness',
    0,
    True,
    '%s/privateDemographics/models/waterbirds/erm_num_epoch_360_batch_size_128_lr_1e-05_subsample_False_weight_decay_1_best.model' % root_dir,
    123,
    'erm',
    torch.device('cpu'),
)

Representations are loaded from folder /mnt/cloud/yzeng58/privateDemographics/data/waterbirds_resnet50_representation!


In [3]:
results = get_domain_george(
    loader,
    num_domain,
    num_class,
    4,
    device,
    123,
)

AttributeError: 'Tensor' object has no attribute 'items'

In [4]:
import umap

In [10]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [5]:
inputs

array([[0.19409652, 0.30253813, 1.0947552 , ..., 0.10340346, 0.15202883,
        0.17909719],
       [0.22415239, 0.27610916, 0.23466566, ..., 0.41363716, 0.53521764,
        0.22774148],
       [0.0500348 , 0.26553   , 0.48521304, ..., 0.6409122 , 0.31423807,
        0.27291188],
       ...,
       [0.798796  , 0.552743  , 0.19613914, ..., 0.39260322, 0.13164362,
        0.1376287 ],
       [0.68545634, 0.86812115, 0.14870302, ..., 0.32641524, 0.17164503,
        0.24192645],
       [0.9258263 , 0.46162266, 0.32339785, ..., 0.41059187, 0.67685294,
        0.29472074]], dtype=float32)

In [6]:
for y in range(num_class):
    y_idx = idx_class == y
    reducer = umap.UMAP(random_state = seed, n_components = 2, n_neighbors = 10, min_dist = 0)
    umap_labels = reducer.fit_transform(inputs[y_idx])
#     print(np.unique(umap_labels))

In [7]:
print(np.unique(umap_labels))

[ 2.9524755  2.998944   3.016039  ... 12.758354  12.767308  12.779216 ]


In [8]:
umap_labels

array([[ 9.076679 , 11.984409 ],
       [ 8.367124 , 10.402316 ],
       [ 7.5135937, 11.094875 ],
       ...,
       [ 9.7546   , 10.051958 ],
       [ 8.216393 ,  9.572042 ],
       [ 9.030809 , 12.073336 ]], dtype=float32)