In [6]:
import json, os
import numpy as np
from sklearn.metrics.cluster import adjusted_rand_score
from settings import *

In [2]:
def get_stat(dataset):
    try:
        with open('%s/privateDemographics/results/%s/pred_dict_outlier_0.json' % (root_dir, dataset), 'r') as f:
            pred_dict = json.load(f)
    except:
        with open('%s/privateDemographics/results/%s/pred_dict.json' % (root_dir, dataset), 'r') as f:
            pred_dict = json.load(f)

    group = np.load('%s/privateDemographics/results/%s/true_group.npy' % (root_dir, dataset))
    idx_mode = np.load('%s/privateDemographics/results/%s/idx_mode.npy' % (root_dir, dataset))

    train_group = group[idx_mode == 'train']
    train_pred = np.array(pred_dict['train'])
    return train_group, train_pred

# Waterbirds

In [8]:
for file in os.listdir('/mnt/cloud/yzeng58/privateDemographics/results/compas'):
    if file.startswith('clustering'):
        group = np.load(f'/mnt/cloud/yzeng58/privateDemographics/results/compas/{file}')
        print(np.unique(group))


[-1  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22
 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46
 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63]
[-1  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22
 23 24 25 26 27 28 29 30]
[-1  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[-1  0  1  2  3  4  5  6  7  8  9]
[-1  0  1  2  3  4  5  6]
[-1  0  1  2  3  4  5]
[-1  0  1  2  3]
[-1  0  1  2]
[-1  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22
 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46
 47 48 49 50 51 52 53 54 55 56 57]
[-1  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22
 23 24 25 26 27]
[-1  0  1  2  3  4  5  6  7  8  9 10 11]
[-1  0  1  2  3  4  5  6  7  8  9]
[-1  0  1  2  3  4  5  6  7  8]
[-1  0  1  2  3  4  5  6]
[-1  0  1  2  3  4]
[-1  0  1  2]
[-1  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22
 23 24 25 26 27 28 29 30 

In [26]:
train_group, train_pred = get_stat(dataset = 'waterbirds')

In [27]:
# check minority group
idx, pro = np.unique(train_group, return_counts = True)
idx, pro/pro.sum()

(array([0, 1, 2, 3]), array([0.72950991, 0.03837331, 0.01167883, 0.22043796]))

In [28]:
idx, pro = np.unique(train_pred, return_counts = True)
idx, pro/pro.sum()

(array([-1.,  0.,  1.,  2.]),
 array([0.06131387, 0.71345151, 0.19144943, 0.03378519]))

In [29]:
a = (train_group == 1) | (train_group == 2)
b = (train_pred == 2)
(a & b).sum() / max(a.sum(), b.sum())

0.14166666666666666

In [30]:
adjusted_rand_score(train_group, train_pred)

0.8084822954916884

# Civilcomments

In [8]:
train_group, train_pred = get_stat(dataset = 'civilcomments')

In [9]:
# check minority group
idx, pro = np.unique(train_group, return_counts = True)
idx, pro/pro.sum()

(array([0, 1, 8, 9]), array([0.33577785, 0.55079952, 0.06610219, 0.04732045]))

In [10]:
idx, pro = np.unique(train_pred, return_counts = True)
idx, pro/pro.sum()

(array([0., 1., 2., 3.]),
 array([8.38561839e-01, 4.75880731e-02, 4.27448911e-04, 1.13422639e-01]))

In [11]:
a = (train_group == 8) | (train_group == 9)
b = (train_pred == 1) |  (train_pred == 2) 
(a & b).sum() / max(a.sum(), b.sum())

0.0

In [12]:
adjusted_rand_score(train_group, train_pred)

0.2862698928952462

# Synthetic

In [13]:
train_group, train_pred = get_stat(dataset = 'synthetic')

In [14]:
# check minority group
idx, pro = np.unique(train_group, return_counts = True)
idx, pro/pro.sum()

(array([0, 1, 2, 3, 4, 5]),
 array([0.03846154, 0.07692308, 0.38461538, 0.03846154, 0.07692308,
        0.38461538]))

In [15]:
idx, pro = np.unique(train_pred, return_counts = True)
idx, pro/pro.sum()

(array([0., 1., 2., 3., 4., 5.]),
 array([0.00076923, 0.42692308, 0.07230769, 0.02769231, 0.41230769,
        0.06      ]))

In [16]:
a = (train_group == 0) | (train_group == 1) | (train_group == 3) | (train_group == 4)
b = (train_pred == 3) |  (train_pred == 2) |  (train_pred == 5) |  (train_pred == 6) 
(a & b).sum() / max(a.sum(), b.sum())

0.69

In [17]:
adjusted_rand_score(train_group, train_pred)

0.8539216141954911

# MultiNLI

In [18]:
train_group, train_pred = get_stat(dataset = 'multinli')

In [19]:
# check minority group
idx, pro = np.unique(train_group, return_counts = True)
idx, pro/pro.sum()

(array([0, 1, 2, 3, 4, 5]),
 array([0.27887959, 0.05411907, 0.32679035, 0.00737723, 0.32317206,
        0.0096617 ]))

In [20]:
idx, pro = np.unique(train_pred, return_counts = True)
idx, pro/pro.sum()

(array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
        13., 14., 15., 16., 17., 18., 19., 20., 22., 23., 24., 25., 27.,
        28., 29., 30., 31., 32., 33.]),
 array([6.75445617e-02, 2.65163090e-01, 1.45507457e-05, 1.94009943e-05,
        4.85024858e-06, 1.45507457e-05, 9.70049715e-06, 1.94009943e-05,
        1.45507457e-05, 1.45507457e-05, 1.45507457e-05, 4.85024858e-06,
        9.70049715e-06, 1.94009943e-05, 9.70049715e-06, 1.45507457e-05,
        9.70049715e-06, 1.45507457e-05, 9.70049715e-06, 4.85024858e-06,
        1.45507457e-05, 1.45507457e-05, 4.85024858e-06, 4.85024858e-06,
        9.70049715e-06, 4.85024858e-06, 4.85024858e-06, 9.70049715e-06,
        1.15857888e-01, 2.18309688e-01, 1.10280102e-01, 2.22553656e-01]))

In [21]:
a = (train_group == 1) | (train_group == 3) | (train_group == 5)
b = np.in1d(train_pred, idx[pro/pro.sum() < 0.1])
(a & b).sum() / max(a.sum(), b.sum())

0.1501601799468339

In [22]:
adjusted_rand_score(train_group, train_pred)

0.6057219637871808

In [10]:
pro

NameError: name 'pro' is not defined